### ISSUE TITLE
Error synching block on stage environment

### ISSUE THREAD

**Issue by pgolovkin** [sora-xor/pricing-server#24]
Error trace
`
2021-09-03 10:22:54,627 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "run_node_processing.py", line 456, in <module>
    asyncio.run(async_main_loop(async_session, args))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "run_node_processing.py", line 419, in async_main_loop
    await async_main(async_session, args.begin, args.clean, args.silent)
  File "run_node_processing.py", line 218, in async_main
    events, res, grouped_events = get_events_from_block(substrate, block)
  File "run_node_processing.py", line 55, in get_events_from_block
    events = substrate.get_events(block_hash)
  File "/home/app/.local/lib/python3.8/site-packages/substrateinterface/base.py", line 1528, in get_events
    storage_obj = self.query(module="System", storage_function="Events", block_hash=block_hash)
  File "/home/app/.local/lib/python3.8/site-packages/substrateinterface/base.py", line 1500, in query
    obj.decode()
  File "/home/app/.local/lib/python3.8/site-packages/scalecodec/base.py", line 434, in decode
    self.value = self.process()
  File "/home/app/.local/lib/python3.8/site-packages/scalecodec/block.py", line 310, in process
    element = self.process_type('EventRecord', metadata=self.metadata)
  File "/home/app/.local/lib/python3.8/site-packages/scalecodec/base.py", line 497, in process_type
    obj.decode(check_remaining=False)
  File "/home/app/.local/lib/python3.8/site-packages/scalecodec/base.py", line 434, in decode
    self.value = self.process()
  File "/home/app/.local/lib/python3.8/site-packages/scalecodec/block.py", line 402, in process
    self.topics = self.process_type('Vec<Hash>').value
  File "/home/app/.local/lib/python3.8/site-packages/scalecodec/base.py", line 497, in process_type
    obj.decode(check_remaining=False)
  File "/home/app/.local/lib/python3.8/site-packages/scalecodec/base.py", line 434, in decode
    self.value = self.process()
  File "/home/app/.local/lib/python3.8/site-packages/scalecodec/types.py", line 768, in process
    element = self.process_type(self.sub_type, metadata=self.metadata)
  File "/home/app/.local/lib/python3.8/site-packages/scalecodec/base.py", line 497, in process_type
    obj.decode(check_remaining=False)
  File "/home/app/.local/lib/python3.8/site-packages/scalecodec/base.py", line 443, in decode
    raise RemainingScaleBytesNotEmptyException(
scalecodec.exceptions.RemainingScaleBytesNotEmptyException: Decoding "H256" - No more bytes available (needed: 650 / total: 645)`

**Comment by pgolovkin** [comment]
Log before it 
`2021-09-03 14:17:42,604 INFO sqlalchemy.engine.Engine SELECT token.id, token.symbol, token.name, token.decimals, token.trade_volume 
FROM token 
WHERE token.id = %s
2021-09-03 14:17:42,604 INFO SELECT token.id, token.symbol, token.name, token.decimals, token.trade_volume 
FROM token 
WHERE token.id = %s
2021-09-03 14:17:42,604 INFO [generated in 0.00025s] (Decimal('904625697166532776746648320380374280103671755200316906558262375061821325312'),)
2021-09-03 14:17:42,604 INFO sqlalchemy.engine.Engine [generated in 0.00025s] (Decimal('904625697166532776746648320380374280103671755200316906558262375061821325312'),)
2021-09-03 14:17:42,606 INFO sqlalchemy.engine.Engine SELECT token.id, token.symbol, token.name, token.decimals, token.trade_volume 
FROM token 
WHERE token.id = %s
2021-09-03 14:17:42,606 INFO sqlalchemy.engine.Engine [cached since 0.002377s ago] (Decimal('904653304151919939001798059403823388205481559636205588104483025158716522496'),)
2021-09-03 14:17:42,606 INFO SELECT token.id, token.symbol, token.name, token.decimals, token.trade_volume 
FROM token 
WHERE token.id = %s
2021-09-03 14:17:42,606 INFO [cached since 0.002377s ago] (Decimal('904653304151919939001798059403823388205481559636205588104483025158716522496'),)
2021-09-03 14:17:42,608 INFO sqlalchemy.engine.Engine SELECT token.id, token.symbol, token.name, token.decimals, token.trade_volume 
FROM token 
WHERE token.id = %s
2021-09-03 14:17:42,608 INFO sqlalchemy.engine.Engine [cached since 0.003798s ago] (Decimal('904660205898266729565585494159685665230934010745177758491038187682940321792'),)
2021-09-03 14:17:42,608 INFO SELECT token.id, token.symbol, token.name, token.decimals, token.trade_volume 
FROM token 
WHERE token.id = %s
2021-09-03 14:17:42,608 INFO [cached since 0.003798s ago] (Decimal('904660205898266729565585494159685665230934010745177758491038187682940321792'),)
2021-09-03 14:19:43,316 INFO sqlalchemy.engine.Engine ROLLBACK
2021-09-03 14:19:43,316 INFO ROLLBACK
Traceback (most recent call last):`

**Comment by Tieumsan** [comment]
@ra9mls @vovac12 is it solved by the fix on syncing process from last year ?

**Comment by ra9mls** [comment]
@Tieumsan seems it was fixed, we don't have issues now.
