### ISSUE TITLE
pricing import service is down after runtime update

### ISSUE THREAD

**Issue by f33r0** [sora-xor/pricing-server#74]
**Block 10424836** 
```
2023-05-09 17:33:02,523 INFO Getting events from block 10424836
Traceback (most recent call last):
  File "run_node_processing.py", line 263, in async_main
    block_hash, events, res, grouped_events = get_events_from_block(
  File "run_node_processing.py", line 78, in get_events_from_block
    events = substrate.get_events(block_hash)
  File "/home/app/.local/lib/python3.8/site-packages/substrateinterface/base.py", line 1526, in get_events
    storage_obj = self.query(module="System", storage_function="Events", block_hash=block_hash)
  File "/home/app/.local/lib/python3.8/site-packages/substrateinterface/base.py", line 1462, in query
    obj.decode()
  File "/home/app/.local/lib/python3.8/site-packages/scalecodec/base.py", line 677, in decode
    self.value_serialized = self.process()
  File "/home/app/.local/lib/python3.8/site-packages/scalecodec/types.py", line 830, in process
    element = self.process_type(self.sub_type, metadata=self.metadata)
  File "/home/app/.local/lib/python3.8/site-packages/scalecodec/base.py", line 760, in process_type
    obj.decode(check_remaining=False)
  File "/home/app/.local/lib/python3.8/site-packages/scalecodec/base.py", line 677, in decode
    self.value_serialized = self.process()
  File "/home/app/.local/lib/python3.8/site-packages/scalecodec/types.py", line 2735, in process
    'module_id': value['event']['module_id'],
KeyError: 'module_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_node_processing.py", line 564, in <module>
    asyncio.run(async_main_loop(async_session, args))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "run_node_processing.py", line 527, in async_main_loop
    await async_main(async_session, args.begin, args.clean, args.silent)
  File "run_node_processing.py", line 267, in async_main
    block_hash, events, res, grouped_events = get_events_from_block(
  File "run_node_processing.py", line 78, in get_events_from_block
    events = substrate.get_events(block_hash)
  File "/home/app/.local/lib/python3.8/site-packages/substrateinterface/base.py", line 1526, in get_events
    storage_obj = self.query(module="System", storage_function="Events", block_hash=block_hash)
  File "/home/app/.local/lib/python3.8/site-packages/substrateinterface/base.py", line 1462, in query
    obj.decode()
  File "/home/app/.local/lib/python3.8/site-packages/scalecodec/base.py", line 677, in decode
    self.value_serialized = self.process()
  File "/home/app/.local/lib/python3.8/site-packages/scalecodec/types.py", line 830, in process
    element = self.process_type(self.sub_type, metadata=self.metadata)
  File "/home/app/.local/lib/python3.8/site-packages/scalecodec/base.py", line 760, in process_type
    obj.decode(check_remaining=False)
  File "/home/app/.local/lib/python3.8/site-packages/scalecodec/base.py", line 677, in decode
    self.value_serialized = self.process()
  File "/home/app/.local/lib/python3.8/site-packages/scalecodec/types.py", line 2735, in process
    'module_id': value['event']['module_id'],
KeyError: 'module_id'
```

**Comment by Tieumsan** [comment]
Need to update the substrateinterface library (Python).

**Comment by f33r0** [comment]
Fixed by @pakrentos
