### ISSUE TITLE
pricing import-service carshes

### ISSUE THREAD

**Issue by f33r0** [sora-xor/pricing-server#77]
```
2023-06-01 00:19:36,167 INFO Getting events from block 10753325
2023-06-01 00:19:36,245 INFO ROLLBACK
2023-06-01 00:19:36,245 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "run_node_processing.py", line 564, in <module>
    asyncio.run(async_main_loop(async_session, args))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "run_node_processing.py", line 527, in async_main_loop
    await async_main(async_session, args.begin, args.clean, args.silent)
  File "run_node_processing.py", line 492, in async_main
    amount = int(result['result']['amount']) / DENOM
TypeError: 'NoneType' object is not subscriptable
```

**Comment by f33r0** [comment]
fixed by @pakrentos
