### ISSUE TITLE
Pricing-import service stops with error

### ISSUE THREAD

**Issue by f33r0** [sora-xor/pricing-server#81]
```
2023-09-26 11:57:45,560 INFO ROLLBACK
Traceback (most recent call last):
  File "run_node_processing.py", line 564, in <module>
    asyncio.run(async_main_loop(async_session, args))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "run_node_processing.py", line 527, in async_main_loop
    await async_main(async_session, args.begin, args.clean, args.silent)
  File "run_node_processing.py", line 492, in async_main
    amount = int(result['result']['amount']) / DENOM
TypeError: 'NoneType' object is not subscriptable
```

**Comment by pakrentos** [comment]
Could not reproduce. Pricing server has been roll-backed to the previous tag on the test env
