### ISSUE TITLE
pricing-import-service restarts

### ISSUE THREAD

**Issue by f33r0** [sora-xor/pricing-server#85]
```
2024-01-30 07:57:14,927 INFO Getting events from block 14215245
2024-01-30 07:57:15,167 INFO ROLLBACK
2024-01-30 07:57:15,167 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "run_node_processing.py", line 570, in <module>
    asyncio.run(async_main_loop(async_session, args))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "run_node_processing.py", line 533, in async_main_loop
    await async_main(async_session, args.begin, args.clean, args.silent)
  File "run_node_processing.py", line 494, in async_main
    pair.quote_price = amount if swap[1] == xor_id_int else 1 / amount
decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]
```

**Comment by bragov4ik** [comment]
It seems the problem is with second `swap` call in this block: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws.mof.sora.org#/explorer/query/14215245

it is a swap with an asset called `RENBTC`, which might be worthless. This way it's possible that the `quote` method returns 0 amount which results in this error.

**Comment by bragov4ik** [comment]
> it is a swap with an asset called `RENBTC`, which might be worthless.

it was the other way around: it's too pricey so that `quote(1 xor -> renbtc)=0` (actually it's $\approx 0.63\cdot10^{-18}$, which got rounded down to 0). 
then it tried to find the price in other way which resulted in division by zero
